<?php
// ============================================================
// api/sensors.php  —  IoT Sensor REST API
//
// ── PUBLIC (no authentication) ───────────────────────────
//   GET  ?action=map_data           → all sensors + the latest data
//   GET  ?action=history&id=N       → 24h chart data for sensor N
//
// ── SENSOR SEND (authentication via coordinates) ────────
//   GET  ?action=reading
//        &lat=54.6872000&lng=25.2797000
//        &temperature=21.3&humidity=55.1
//        [&co2=412&pm1=5&pm2_5=8.4&pm10=12&grains=23&radiation=0.12]
//
//   The sensor MUST be pre-registered in the DB.
//   If the sensor is unknown → 403.
//   The first successful record confirms the sensor (confirmed=1).
//
// ── REGISTRATION (via the index.php page or directly) ────
//   GET  ?action=register&lat=54.6872000&lng=25.2797000
//   Creates a DB record (confirmed=0). Within 3 min it must receive
//   at least one ?action=reading, otherwise it is deleted automatically.
//
// ── DELETION ─────────────────────────────────────────────
//   GET  ?action=delete&id=N        → manually delete a sensor
// ============================================================

require_once __DIR__ . '/../includes/config.php';
require_once __DIR__ . '/../includes/cities.php';
require_once __DIR__ . '/../includes/auth.php'; // admin session check (delete/clear)

// Fallback definitions — in case config.php was generated by an older
// admin.php version and lacks these helper functions.
if (!function_exists('setCorsHeaders')) {
    function setCorsHeaders(): void {
        header('Content-Type: application/json; charset=utf-8');
        header('X-Content-Type-Options: nosniff');
        header('Cache-Control: no-store');
        if (($_SERVER['REQUEST_METHOD'] ?? 'GET') === 'OPTIONS') {
            header('Access-Control-Allow-Methods: GET, OPTIONS');
            header('Access-Control-Allow-Headers: Content-Type');
            exit(0);
        }
    }
}
if (!function_exists('jsonResponse')) {
    function jsonResponse(mixed $data, int $status = 200): never {
        http_response_code($status);
        echo json_encode($data, JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT);
        exit;
    }
}
if (!function_exists('db')) {
    function db(): PDO {
        static $pdo = null;
        if ($pdo === null) {
            $dsn = sprintf('mysql:host=%s;dbname=%s;charset=%s', DB_HOST, DB_NAME, DB_CHARSET);
            $pdo = new PDO($dsn, DB_USER, DB_PASS, [
                PDO::ATTR_ERRMODE            => PDO::ERRMODE_EXCEPTION,
                PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
                PDO::ATTR_EMULATE_PREPARES   => false,
            ]);
        }
        return $pdo;
    }
}

setCorsHeaders();

// ── Production error protection (E1/E3) ───────────────────
// Do not reveal paths, stack traces or DB structure to the client.
// Errors are logged on the server; the client gets a generic message.
error_reporting(E_ALL);
ini_set('display_errors', '0');
ini_set('log_errors', '1');

set_exception_handler(function (Throwable $e) {
    error_log('[IoT API] ' . $e->getMessage() . ' @ ' . $e->getFile() . ':' . $e->getLine());

    // 5.4 Optional error-tracking integration (Sentry or any webhook).
    // If ERROR_WEBHOOK_URL is set in the config (e.g. a Sentry "store" or
    // Slack/Discord webhook), the error is sent there. Silent, non-blocking.
    if (defined('ERROR_WEBHOOK_URL') && ERROR_WEBHOOK_URL !== '') {
        @reportError($e);
    }

    http_response_code(500);
    header('Content-Type: application/json; charset=utf-8');
    echo json_encode(['error' => 'Serverio klaida. Bandykite vėliau.', 'code' => 'server_error'], JSON_UNESCAPED_UNICODE);
    exit;
});

/**
 * 5.4 Sends the error to ERROR_WEBHOOK_URL (Sentry/Slack/Discord etc.).
 * Short timeout so it does not block the response; errors here are ignored.
 */
function reportError(Throwable $e): void {
    $payload = json_encode([
        'message'   => $e->getMessage(),
        'file'      => $e->getFile() . ':' . $e->getLine(),
        'timestamp' => date('c'),
        'url'       => $_SERVER['REQUEST_URI'] ?? '',
    ], JSON_UNESCAPED_UNICODE);
    $ctx = stream_context_create([
        'http' => [
            'method'  => 'POST',
            'header'  => "Content-Type: application/json\r\n",
            'content' => $payload,
            'timeout' => 2,
        ],
    ]);
    @file_get_contents(ERROR_WEBHOOK_URL, false, $ctx);
}

$action = $_GET['action'] ?? $_POST['action'] ?? '';

// ─────────────────────────────────────────────────────────
// Helper: float from GET, null if missing/invalid
// ─────────────────────────────────────────────────────────
function getFloat(string $key, float $min, float $max): ?float {
    if (!isset($_GET[$key]) || $_GET[$key] === '') return null;
    $v = filter_var($_GET[$key], FILTER_VALIDATE_FLOAT);
    if ($v === false || $v < $min || $v > $max) return null;
    return round($v, 7);
}

// MAC address validation and normalization.
// Accepts AA:BB:CC:DD:EE:FF, AA-BB-..., aabbcc... → returns uppercase
// with colons, or '' if invalid/not provided.
function getMac(string $key = 'mac'): string {
    $raw = $_GET[$key] ?? '';
    if ($raw === '') return '';
    // Remove separators, keep only hex
    $hex = preg_replace('/[^0-9A-Fa-f]/', '', $raw);
    if (strlen($hex) !== 12) return ''; // invalid → empty
    $hex = strtoupper($hex);
    return implode(':', str_split($hex, 2)); // AA:BB:CC:DD:EE:FF
}

/**
 * 1.4 Rate limiting (slankiojantis fiksuotas langas, DB pagrindu).
 * Returns true if the request is ALLOWED, false if the limit is exceeded.
 * $key — a unique key (e.g. "read:1.2.3.4"); $max — max requests
 * per $windowSec-second window. Concurrency-safe (INSERT ... ON
 * DUPLICATE KEY UPDATE atomically increments the counter).
 */
function rateLimitOk(string $key, int $max, int $windowSec): bool {
    try {
        $now = time();
        $windowStart = $now - ($now % $windowSec); // window start
        $stmt = db()->prepare(
            "INSERT INTO rate_limits (rl_key, window_start, counter)
             VALUES (:k, :ws, 1)
             ON DUPLICATE KEY UPDATE
                counter = IF(window_start = :ws2, counter + 1, 1),
                window_start = IF(window_start = :ws3, window_start, :ws4)"
        );
        $stmt->execute([
            ':k' => $key, ':ws' => $windowStart,
            ':ws2' => $windowStart, ':ws3' => $windowStart, ':ws4' => $windowStart,
        ]);
        // Read the current counter
        $check = db()->prepare("SELECT counter FROM rate_limits WHERE rl_key = :k");
        $check->execute([':k' => $key]);
        $count = (int)$check->fetchColumn();
        return $count <= $max;
    } catch (PDOException) {
        // If the table is missing (old schema) — do not block
        return true;
    }
}

/**
 * Visitor IP (rate limiting and audit log).
 */
function clientIpApi(): string {
    return $_SERVER['REMOTE_ADDR'] ?? '0.0.0.0';
}

/**
 * 2.2 Audit log entry (sensitive admin actions).
 */
function auditLog(string $action, ?int $targetId = null, ?string $details = null): void {
    try {
        db()->prepare(
            "INSERT INTO audit_log (actor_ip, action, target_id, details)
             VALUES (:ip, :action, :tid, :details)"
        )->execute([
            ':ip' => clientIpApi(), ':action' => $action,
            ':tid' => $targetId, ':details' => $details,
        ]);
    } catch (PDOException) { /* sena schema — tyliai praleisti */ }
}

/**
 * Safely splits "1,2,3" into a unique array of positive integer IDs.
 * Limits to 1000 elements (protection against an oversized request).
 */
function parseIdList(string $raw): array {
    $ids = [];
    foreach (explode(',', $raw) as $part) {
        $n = (int)trim($part);
        if ($n > 0) $ids[$n] = true; // raktas = dedupe
    }
    return array_slice(array_keys($ids), 0, 1000);
}

// ─────────────────────────────────────────────────────────
// GET map_data — all active sensors + the latest record
// ─────────────────────────────────────────────────────────
// ─────────────────────────────────────────────────────────
// 5.1 GET health — DB and disk status check
// ─────────────────────────────────────────────────────────
if ($action === 'health') {
    $status = ['status' => 'ok', 'checks' => []];
    $code = 200;

    // DB connection
    try {
        db()->query('SELECT 1');
        $status['checks']['database'] = 'ok';
    } catch (\Throwable $e) {
        $status['checks']['database'] = 'fail';
        $status['status'] = 'degraded';
        $code = 503;
    }

    // Disk space (if < 50 MB free — a warning)
    $free = @disk_free_space(__DIR__);
    if ($free !== false) {
        $freeMb = round($free / 1048576, 1);
        $status['checks']['disk_free_mb'] = $freeMb;
        if ($freeMb < 50) {
            $status['checks']['disk'] = 'low';
            if ($status['status'] === 'ok') $status['status'] = 'warning';
        } else {
            $status['checks']['disk'] = 'ok';
        }
    }

    $status['timestamp'] = date('c');
    jsonResponse($status, $code);
}

// ─────────────────────────────────────────────────────────
// 4.5 GET export — export a sensor's readings (CSV or JSON)
//     ?action=export&id=N&format=csv|json[&hours=24]
// ─────────────────────────────────────────────────────────
// ─────────────────────────────────────────────────────────
// 5.2 GET stats — admin metrics (sensor count, records/day, offline %)
// ─────────────────────────────────────────────────────────
if ($action === 'stats') {
    requireAdminApi(); // logged-in administrator only

    try {
        $total = (int)db()->query("SELECT COUNT(*) FROM sensors WHERE confirmed = 1")->fetchColumn();
        $pending = (int)db()->query("SELECT COUNT(*) FROM sensors WHERE confirmed = 0")->fetchColumn();
        $offline = (int)db()->query(
            "SELECT COUNT(*) FROM sensors WHERE confirmed = 1
             AND last_seen < DATE_SUB(NOW(), INTERVAL " . (int)SENSOR_TIMEOUT_MIN . " MINUTE)"
        )->fetchColumn();
        $totalReadings = (int)db()->query("SELECT COUNT(*) FROM readings")->fetchColumn();
        $readingsToday = (int)db()->query(
            "SELECT COUNT(*) FROM readings WHERE recorded_at >= CURDATE()"
        )->fetchColumn();
        $indoor = (int)db()->query("SELECT COUNT(*) FROM sensors WHERE confirmed=1 AND is_outdoor=0")->fetchColumn();
        $outdoor = (int)db()->query("SELECT COUNT(*) FROM sensors WHERE confirmed=1 AND is_outdoor=1")->fetchColumn();
    } catch (\Throwable $e) {
        // DB not configured yet or unreachable — return a clear status
        jsonResponse([
            'error' => 'Duomenų bazė nepasiekiama. Užbaikite sąranką (1–2 žingsniai).',
            'code'  => 'db_unavailable',
        ], 200); // 200 so the frontend shows a message, not an error
    }

    jsonResponse([
        'sensors_total'    => $total,
        'sensors_pending'  => $pending,
        'sensors_offline'  => $offline,
        'offline_percent'  => $total > 0 ? round($offline / $total * 100, 1) : 0,
        'sensors_indoor'   => $indoor,
        'sensors_outdoor'  => $outdoor,
        'readings_total'   => $totalReadings,
        'readings_today'   => $readingsToday,
        'capacity_used'    => round($total / 49800 * 100, 2), // % of the 49,800 limit
        'timestamp'        => date('c'),
    ]);
}

if ($action === 'export') {
    $id = (int)($_GET['id'] ?? 0);
    $format = ($_GET['format'] ?? 'json') === 'csv' ? 'csv' : 'json';
    $hours = max(1, min(8760, (int)($_GET['hours'] ?? 24)));

    if ($id <= 0) jsonResponse(['error' => 'Trūksta arba neteisingas id'], 400);

    $stmt = db()->prepare("
        SELECT recorded_at, temperature, humidity, co2,
               pm1, pm2_5, pm10, grains, radiation,
               alcohol, methane, propane, butane, lpg, hydrogen,
               co, smoke, ammonia, nox, benzene, air_quality, co2_equiv
        FROM readings
        WHERE sensor_id = :id
          AND recorded_at >= DATE_SUB(NOW(), INTERVAL :h HOUR)
        ORDER BY recorded_at ASC
    ");
    $stmt->execute([':id' => $id, ':h' => $hours]);
    $rows = $stmt->fetchAll();
    // recorded_at → ISO 8601 UTC (with "Z") — an unambiguous format for export
    foreach ($rows as &$r) {
        $r['recorded_at'] = toIsoUtc($r['recorded_at'] ?? null);
    }
    unset($r);

    if ($format === 'csv') {
        header('Content-Type: text/csv; charset=utf-8');
        header("Content-Disposition: attachment; filename=sensor_{$id}_readings.csv");
        $out = fopen('php://output', 'w');
        fputcsv($out, ['recorded_at','temperature','humidity','co2','pm1','pm2_5','pm10','grains','radiation',
                       'alcohol','methane','propane','butane','lpg','hydrogen','co','smoke',
                       'ammonia','nox','benzene','air_quality','co2_equiv']);
        foreach ($rows as $r) fputcsv($out, $r);
        fclose($out);
        exit;
    }

    header('Content-Type: application/json; charset=utf-8');
    header("Content-Disposition: attachment; filename=sensor_{$id}_readings.json");
    echo json_encode([
        'sensor_id' => $id,
        'hours'     => $hours,
        'count'     => count($rows),
        'readings'  => $rows,
    ], JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT);
    exit;
}

// ─────────────────────────────────────────────────────────
// 4.3 GET stream — Server-Sent Events (SSE) realaus laiko atnaujinimai.
//     Instead of 30s polling, the browser keeps an open connection and gets new
//     map_data every few seconds. Sends only when data changes
//     (based on the latest recorded_at) — saves bandwidth.
// ─────────────────────────────────────────────────────────
if ($action === 'stream') {
    // CRITICAL: release the session lock IMMEDIATELY. PHP sessions are
    // file-locked — while SSE keeps the session open, ALL other requests
    // of the same user (pages, forms, API) block
    // waiting for the lock. session_write_close() releases the lock but
    // leaves the $_SESSION data readable in this process.
    if (session_status() === PHP_SESSION_ACTIVE) {
        session_write_close();
    }

    // SSE headers
    header('Content-Type: text/event-stream');
    header('Cache-Control: no-cache');
    header('Connection: keep-alive');
    header('X-Accel-Buffering: no'); // disable nginx buffering

    @set_time_limit(0);
    ignore_user_abort(false);

    // Function for assembling map_data (same logic as the map_data endpoint)
    $fetchMapData = function (): array {
        $sql = "
            SELECT s.id,
                CONCAT(s.city_prefix, (
                    SELECT COUNT(*) FROM sensors s2
                    WHERE s2.city_prefix = s.city_prefix AND s2.id <= s.id
                )) AS label,
                s.lat, s.lng, s.mac, s.is_outdoor, s.last_seen,
                CASE WHEN s.last_seen >= DATE_SUB(NOW(), INTERVAL :tmin MINUTE)
                     THEN 1 ELSE 0 END AS online,
                r.temperature, r.humidity, r.co2, r.pm1, r.pm2_5,
                r.pm10, r.grains, r.radiation,
                r.alcohol, r.methane, r.propane, r.butane, r.lpg, r.hydrogen,
                r.co, r.smoke, r.ammonia, r.nox, r.benzene, r.air_quality, r.co2_equiv,
                r.recorded_at
            FROM sensors s
            LEFT JOIN readings r ON r.id = (
                SELECT id FROM readings WHERE sensor_id = s.id
                ORDER BY recorded_at DESC LIMIT 1
            )
            WHERE s.confirmed = 1
            ORDER BY s.id ASC
        ";
        $stmt = db()->prepare($sql);
        $stmt->execute([':tmin' => SENSOR_TIMEOUT_MIN]);
        $sensors = $stmt->fetchAll();
        foreach ($sensors as &$s) {
            $s['lat'] = (float)$s['lat'];
            $s['lng'] = (float)$s['lng'];
            $s['last_seen']   = toIsoUtc($s['last_seen'] ?? null);
            $s['recorded_at'] = toIsoUtc($s['recorded_at'] ?? null);
        }
        unset($s);
        return $sensors;
    };

    // Last-change marker (so we send only on change)
    $lastHash = '';
    $iterations = 0;
    $maxIterations = 720; // ~1 h (every 5s) — then the browser switches automatically

    while ($iterations < $maxIterations) {
        if (connection_aborted()) break;

        try {
            $sensors = $fetchMapData();
            $hash = md5(json_encode($sensors));

            // Send only if the data changed (or the first time)
            if ($hash !== $lastHash) {
                $lastHash = $hash;
                echo "event: update\n";
                echo 'data: ' . json_encode([
                    'sensors' => $sensors,
                    'count'   => count($sensors),
                    'ts'      => date('c'),
                ]) . "\n\n";
            } else {
                // Heartbeat (comment) so the connection stays open
                echo ": heartbeat\n\n";
            }
        } catch (\Throwable $e) {
            echo "event: error\n";
            echo 'data: ' . json_encode(['error' => 'stream_error']) . "\n\n";
        }

        if (ob_get_level() > 0) @ob_flush();
        @flush();

        sleep(5); // check every 5 seconds
        $iterations++;
    }
    // On reaching the limit — tell the client the connection ended cleanly.
    // The client will switch to polling instead of reconnecting endlessly.
    echo "event: bye\n";
    echo "data: {\"reason\":\"max_duration\"}\n\n";
    if (ob_get_level() > 0) @ob_flush();
    @flush();
    exit;
}

if ($action === 'map_data') {
    // ALL confirmed sensors are shown — online and offline.
    // online  = last_seen <= SENSOR_TIMEOUT_MIN min atgal
    // offline = last_seen >  SENSOR_TIMEOUT_MIN min ago (silent, but history kept)

    // 4.1 Viewport (bbox) filtering + pagination for high density.
    // If sw_lat/sw_lng/ne_lat/ne_lng are provided — return only those in that
    // bounding box. limit/offset for pagination.
    $bboxSql = '';
    $bboxParams = [];
    $swLat = getFloat('sw_lat', -90, 90);
    $swLng = getFloat('sw_lng', -180, 180);
    $neLat = getFloat('ne_lat', -90, 90);
    $neLng = getFloat('ne_lng', -180, 180);
    if ($swLat !== null && $swLng !== null && $neLat !== null && $neLng !== null) {
        $bboxSql = " AND s.lat BETWEEN :swlat AND :nelat AND s.lng BETWEEN :swlng AND :nelng";
        $bboxParams = [
            ':swlat' => $swLat, ':nelat' => $neLat,
            ':swlng' => $swLng, ':nelng' => $neLng,
        ];
    }

    // Pagination (optional). limit 0 or unspecified = all.
    $limit  = max(0, min(50000, (int)($_GET['limit'] ?? 0)));
    $offset = max(0, (int)($_GET['offset'] ?? 0));
    $limitSql = $limit > 0 ? " LIMIT $limit OFFSET $offset" : '';

    $sql = "
        SELECT
            s.id,
            CONCAT(s.city_prefix, (
                SELECT COUNT(*) FROM sensors s2
                WHERE s2.city_prefix = s.city_prefix AND s2.id <= s.id
            )) AS label,
            s.city_prefix,
            s.lat, s.lng, s.mac, s.is_outdoor,
            (s.secret IS NOT NULL) AS has_secret,
            s.registered_at, s.last_seen,
            CASE
                WHEN s.last_seen >= DATE_SUB(NOW(), INTERVAL :tmin MINUTE)
                THEN 1 ELSE 0
            END AS online,
            r.temperature, r.humidity, r.co2,
            r.pm1, r.pm2_5, r.pm10, r.grains, r.radiation,
            r.alcohol, r.methane, r.propane, r.butane, r.lpg, r.hydrogen,
            r.co, r.smoke, r.ammonia, r.nox, r.benzene, r.air_quality, r.co2_equiv,
            r.recorded_at
        FROM sensors s
        LEFT JOIN readings r ON r.id = (
            SELECT id FROM readings
            WHERE sensor_id = s.id
            ORDER BY recorded_at DESC
            LIMIT 1
        )
        WHERE s.confirmed = 1{$bboxSql}
        ORDER BY s.id ASC{$limitSql}
    ";
    $stmt = db()->prepare($sql);
    $stmt->execute(array_merge([':tmin' => SENSOR_TIMEOUT_MIN], $bboxParams));
    $sensors = $stmt->fetchAll();

    $counts = [];
    foreach (db()->query(
        "SELECT sensor_id, COUNT(*) AS n FROM readings GROUP BY sensor_id"
    )->fetchAll() as $row) {
        $counts[$row['sensor_id']] = (int)$row['n'];
    }

    foreach ($sensors as &$s) {
        $s['lat']           = (float)$s['lat'];
        $s['lng']           = (float)$s['lng'];
        $s['reading_count'] = $counts[$s['id']] ?? 0;
        $s['has_secret']    = (int)($s['has_secret'] ?? 0); // HMAC enabled flag (secret never exposed)
        // Time fields → ISO 8601 UTC (with "Z") so the browser converts to local time
        $s['last_seen']     = toIsoUtc($s['last_seen'] ?? null);
        $s['registered_at'] = toIsoUtc($s['registered_at'] ?? null);
        $s['recorded_at']   = toIsoUtc($s['recorded_at'] ?? null);
    }
    unset($s);

    // Total number of confirmed sensors (for pagination)
    $total = (int)db()->query("SELECT COUNT(*) FROM sensors WHERE confirmed = 1")->fetchColumn();

    jsonResponse([
        'sensors'  => $sensors,
        'count'    => count($sensors),
        'total'    => $total,
        'bbox'     => $bboxSql !== '',
        'paginated'=> $limit > 0,
    ]);
}

// ─────────────────────────────────────────────────────────
// GET history — 24h data for a single sensor (for the chart)
// ─────────────────────────────────────────────────────────
if ($action === 'history') {
    $id = (int)($_POST['id'] ?? $_GET['id'] ?? 0);
    if ($id <= 0) jsonResponse(['error' => 'Trūksta arba neteisingas id'], 400);

    // Whitelisted periods → [hours back, bucket seconds (0 = raw points)].
    // Long ranges are averaged into time buckets so a year-long chart returns
    // a few hundred points instead of tens of thousands.
    $periods = [
        '1d'   => [24,    0],       // 1 diena  — raw
        '1w'   => [168,   3600],    // 1 savaitė — 1 h buckets  (~168 pts)
        '2w'   => [336,   7200],    // 2 savaitės — 2 h buckets (~168 pts)
        '1mo'  => [720,   21600],   // 1 mėnuo  — 6 h buckets   (~120 pts)
        '3mo'  => [2160,  86400],   // 3 mėnesiai — 1 d buckets (~90 pts)
        '6mo'  => [4320,  86400],   // 6 mėnesiai — 1 d buckets (~180 pts)
        '12mo' => [8760,  86400],   // 12 mėnesių — 1 d buckets (~365 pts)
    ];
    $period = (string)($_GET['period'] ?? $_POST['period'] ?? '1d');
    if (!isset($periods[$period])) $period = '1d';
    [$hours, $bucket] = $periods[$period];

    if ($bucket > 0) {
        // $bucket is a whitelisted integer constant → safe to inline.
        $bs = (int)$bucket;
        $stmt = db()->prepare("
            SELECT FROM_UNIXTIME(FLOOR(UNIX_TIMESTAMP(recorded_at)/$bs)*$bs) AS recorded_at,
                   ROUND(AVG(temperature),2) AS temperature,
                   ROUND(AVG(humidity),2)    AS humidity,
                   ROUND(AVG(co2),1)         AS co2,
                   ROUND(AVG(pm1),2)         AS pm1,
                   ROUND(AVG(pm2_5),2)       AS pm2_5,
                   ROUND(AVG(pm10),2)        AS pm10,
                   ROUND(AVG(grains),2)      AS grains,
                   ROUND(AVG(radiation),4)   AS radiation,
                   ROUND(AVG(alcohol),2)     AS alcohol,
                   ROUND(AVG(methane),2)     AS methane,
                   ROUND(AVG(propane),2)     AS propane,
                   ROUND(AVG(butane),2)      AS butane,
                   ROUND(AVG(lpg),2)         AS lpg,
                   ROUND(AVG(hydrogen),2)    AS hydrogen,
                   ROUND(AVG(co),2)          AS co,
                   ROUND(AVG(smoke),2)       AS smoke,
                   ROUND(AVG(ammonia),2)     AS ammonia,
                   ROUND(AVG(nox),2)         AS nox,
                   ROUND(AVG(benzene),2)     AS benzene,
                   ROUND(AVG(air_quality),2) AS air_quality,
                   ROUND(AVG(co2_equiv),2)   AS co2_equiv
            FROM readings
            WHERE sensor_id = :id
              AND recorded_at >= DATE_SUB(NOW(), INTERVAL :h HOUR)
            GROUP BY FLOOR(UNIX_TIMESTAMP(recorded_at)/$bs)
            ORDER BY recorded_at ASC
        ");
    } else {
        $stmt = db()->prepare("
            SELECT recorded_at,
                   temperature, humidity, co2,
                   pm1, pm2_5, pm10, grains, radiation,
                   alcohol, methane, propane, butane, lpg, hydrogen,
                   co, smoke, ammonia, nox, benzene, air_quality, co2_equiv
            FROM readings
            WHERE sensor_id = :id
              AND recorded_at >= DATE_SUB(NOW(), INTERVAL :h HOUR)
            ORDER BY recorded_at ASC
        ");
    }
    $stmt->execute([':id' => $id, ':h' => $hours]);
    $points = $stmt->fetchAll();
    // recorded_at → ISO 8601 UTC (with "Z") so chart times are shown in
    // the user's local time (the browser converts via toLocaleString)
    foreach ($points as &$p) {
        $p['recorded_at'] = toIsoUtc($p['recorded_at'] ?? null);
    }
    unset($p);

    jsonResponse(['sensor_id' => $id, 'period' => $period, 'hours' => $hours, 'points' => $points]);
}

// ─────────────────────────────────────────────────────────
// GET averages — averaged metric values over a chosen time period,
//   respecting the region (city_prefix) and indoor/outdoor filters.
//     period   = 4h|6h|12h|24h|7d|30d|90d|180d|365d|all
//     region   = city_prefix (e.g. "VLN") or "all"
//     location = all|indoor|outdoor
//   "all" = from the very first reading (first sensor start).
// ─────────────────────────────────────────────────────────
if ($action === 'averages') {
    // Whitelisted period → MySQL interval (value + unit). Values are constants,
    // so they are safe to interpolate; user input is matched against the keys.
    $periods = [
        '4h'  => [4,   'HOUR'], '6h'   => [6,   'HOUR'], '12h'  => [12,  'HOUR'],
        '24h' => [24,  'HOUR'], '7d'   => [7,   'DAY'],  '30d'  => [30,  'DAY'],
        '90d' => [90,  'DAY'],  '180d' => [180, 'DAY'],  '365d' => [365, 'DAY'],
    ];
    $period = (string)($_GET['period'] ?? '24h');
    if ($period !== 'all' && !isset($periods[$period])) $period = '24h';

    $where  = ['s.confirmed = 1'];
    $params = [];

    // Region (city_prefix) — same values as the map's region filter.
    $region = strtoupper(trim((string)($_GET['region'] ?? 'all')));
    if ($region !== '' && $region !== 'ALL' && preg_match('/^[A-Z0-9]{1,10}$/', $region)) {
        $where[] = 's.city_prefix = :region';
        $params[':region'] = $region;
    }

    // Indoor / outdoor — mirrors the map's location filter.
    $location = strtolower(trim((string)($_GET['location'] ?? 'all')));
    if ($location === 'indoor')  $where[] = 's.is_outdoor = 0';
    if ($location === 'outdoor') $where[] = 's.is_outdoor = 1';

    // Time window ('all' = no lower bound).
    if ($period !== 'all') {
        [$n, $unit] = $periods[$period];
        $where[] = "r.recorded_at >= DATE_SUB(NOW(), INTERVAL $n $unit)";
    }

    $metrics = ['temperature', 'humidity', 'co2', 'pm1', 'pm2_5', 'pm10', 'grains', 'radiation',
                'alcohol', 'methane', 'propane', 'butane', 'lpg', 'hydrogen', 'co', 'smoke',
                'ammonia', 'nox', 'benzene', 'air_quality', 'co2_equiv'];
    $selects = [];
    foreach ($metrics as $m) {
        $selects[] = "AVG(r.$m) AS {$m}_avg, COUNT(r.$m) AS {$m}_n";
    }
    $sql = "SELECT " . implode(', ', $selects) . ",
                   COUNT(DISTINCT r.sensor_id) AS sensor_count,
                   COUNT(*) AS reading_count,
                   MIN(r.recorded_at) AS first_at, MAX(r.recorded_at) AS last_at
            FROM readings r
            JOIN sensors s ON r.sensor_id = s.id
            WHERE " . implode(' AND ', $where);
    $stmt = db()->prepare($sql);
    $stmt->execute($params);
    $row = $stmt->fetch() ?: [];

    $out = [];
    foreach ($metrics as $m) {
        $n = (int)($row["{$m}_n"] ?? 0);
        $out[$m] = [
            'avg'   => ($n > 0 && $row["{$m}_avg"] !== null) ? round((float)$row["{$m}_avg"], 2) : null,
            'count' => $n,
        ];
    }
    jsonResponse([
        'period'        => $period,
        'region'        => ($region === '' || $region === 'ALL') ? 'all' : $region,
        'location'      => in_array($location, ['indoor', 'outdoor'], true) ? $location : 'all',
        'sensor_count'  => (int)($row['sensor_count'] ?? 0),
        'reading_count' => (int)($row['reading_count'] ?? 0),
        'first_at'      => toIsoUtc($row['first_at'] ?? null),
        'last_at'       => toIsoUtc($row['last_at'] ?? null),
        'metrics'       => $out,
    ]);
}

// ─────────────────────────────────────────────────────────
// GET reading — a sensor sends data
//
// Privalomi parametrai: lat, lng
// At least one metric parameter: temperature, humidity, ...
//
// URL pavyzdys:
//   /api/sensors.php?action=reading
//     &lat=54.6872000&lng=25.2797000
//     &temperature=21.3&humidity=55.1&co2=412
// ─────────────────────────────────────────────────────────
if ($action === 'reading') {
    $lat = getFloat('lat', -90,  90);
    $lng = getFloat('lng', -180, 180);
    $mac = getMac('mac');

    if ($lat === null || $lng === null || $mac === '') {
        jsonResponse([
            'error' => 'lat, lng ir mac privalomi',
            'pvz'   => '?action=reading&lat=54.6872000&lng=25.2797000&mac=AA:BB:CC:DD:EE:FF&temperature=21.3&humidity=55.1'
        ], 400);
    }

    // 1.4 Rate limiting: a sensor must send no more than once per 5 min.
    // Keyed by MAC (more precise than IP, since several sensors may be behind NAT).
    // Allow up to 2 requests per 5-min window (margin for retransmissions).
    if (!rateLimitOk('read:' . $mac, 2, 300)) {
        jsonResponse([
            'error' => 'Per dažnai. Jutiklis turi siųsti ne dažniau kaip kartą per 5 minutes.',
            'code'  => 'rate_limited',
        ], 429);
    }

    // 1. Exact match: a sensor with this lat+lng+mac is already confirmed.
    $stmt = db()->prepare(
        "SELECT id, secret FROM sensors WHERE lat = :lat AND lng = :lng AND mac = :mac"
    );
    $stmt->execute([':lat' => $lat, ':lng' => $lng, ':mac' => $mac]);
    $sensor = $stmt->fetch();

    if ($sensor) {
        $sensorId = (int)$sensor['id'];

        // 1.3 HMAC signature verification (optional).
        // If the sensor has a `secret`, the request MUST include a valid
        // `sig` parameter = HMAC-SHA256(lat|lng|mac, secret). Protects against
        // forged readings even if the coordinates and MAC are known.
        //
        // IMPORTANT: the signature uses the RAW GET values, exactly as
        // sent by the sensor (e.g. "54.6872000"), NOT a processed float,
        // so the signature matches the firmware (String(lat, 7)). The MAC is normalized
        // to uppercase with colons on both sides.
        if (!empty($sensor['secret'])) {
            $sig = $_GET['sig'] ?? $_POST['sig'] ?? '';
            $rawLat = trim((string)($_GET['lat'] ?? $_POST['lat'] ?? ''));
            $rawLng = trim((string)($_GET['lng'] ?? $_POST['lng'] ?? ''));
            $payload = $rawLat . '|' . $rawLng . '|' . $mac;
            $expected = hash_hmac('sha256', $payload, $sensor['secret']);
            if (!is_string($sig) || !hash_equals($expected, strtolower($sig))) {
                jsonResponse([
                    'error' => 'Neteisingas arba trūkstamas parašas (sig).',
                    'code'  => 'invalid_signature',
                ], 401);
            }
        }
    } else {
        // 2. No exact match — look for a PENDING (mac IS NULL)
        //    record at those coordinates. The first send "claims" the MAC.
        $pendStmt = db()->prepare(
            "SELECT id FROM sensors
             WHERE lat = :lat AND lng = :lng AND mac IS NULL
             ORDER BY registered_at ASC, id ASC
             LIMIT 1"
        );
        $pendStmt->execute([':lat' => $lat, ':lng' => $lng]);
        $pending = $pendStmt->fetch();

        if (!$pending) {
            // Neither an exact sensor nor a pending record exists
            jsonResponse([
                'error' => 'Jutiklis neužregistruotas. Pirmiau užregistruokite per ?action=register',
                'lat'   => $lat,
                'lng'   => $lng,
                'mac'   => $mac,
            ], 403);
        }

        // Assign the MAC to the pending record (claim the registration)
        // and immediately CONFIRM the sensor (confirmed = 1).
        $sensorId = (int)$pending['id'];
        try {
            db()->prepare("UPDATE sensors SET mac = :mac, confirmed = 1 WHERE id = :id")
               ->execute([':mac' => $mac, ':id' => $sensorId]);
        } catch (PDOException $e) {
            // If the same MAC is already assigned to another record at those coordinates
            jsonResponse([
                'error' => 'Šis MAC jau priskirtas jutikliui tose koordinatėse.',
                'mac'   => $mac,
            ], 409);
        }
    }

    // $sensorId is already set in both branches (exact match or pending).
    // Atnaujinti last_seen

    // Collect metric fields from GET parameters
    $allowed = ['temperature','humidity','co2','pm1','pm2_5','pm10','grains','radiation',
                'alcohol','methane','propane','butane','lpg','hydrogen','co','smoke',
                'ammonia','nox','benzene','air_quality','co2_equiv'];
    $fields  = [];
    $params  = [':sensor_id' => $sensorId];

    foreach ($allowed as $field) {
        if (isset($_GET[$field]) && $_GET[$field] !== '' && is_numeric($_GET[$field])) {
            $fields[]          = $field;
            $params[":$field"] = (float)$_GET[$field];
        }
    }

    if (empty($fields)) {
        jsonResponse([
            'error'   => 'Nėra tinkamų matavimo laukų',
            'galimi'  => $allowed,
            'pvz'     => '&temperature=21.3&humidity=55.1',
        ], 400);
    }

    // Optional device timestamp (UTC) for accurate time correlation. The sensor
    // may send recorded_at as ISO 8601 UTC ("…Z") or a Unix epoch (seconds).
    // Validated to a sane window (≤30 d old, ≤5 min in the future for clock skew);
    // otherwise the column DEFAULT (server time, UTC) is used.
    $recordedAt = null;
    $tsRaw = trim((string)($_GET['recorded_at'] ?? $_GET['ts'] ?? ''));
    if ($tsRaw !== '') {
        $ts = ctype_digit($tsRaw) ? (int)$tsRaw : strtotime($tsRaw);
        if ($ts !== false && $ts > 0) {
            $now = time();
            if ($ts >= $now - 2592000 && $ts <= $now + 300) {
                $recordedAt = gmdate('Y-m-d H:i:s', $ts);
            }
        }
    }

    $cols = implode(', ', $fields);
    $vals = implode(', ', array_map(fn($f) => ":$f", $fields));
    if ($recordedAt !== null) {
        $cols .= ', recorded_at';
        $vals .= ', :recorded_at';
        $params[':recorded_at'] = $recordedAt;
    }

    db()->prepare("INSERT INTO readings (sensor_id, $cols) VALUES (:sensor_id, $vals)")
       ->execute($params);
    $readingId = (int)db()->lastInsertId();

    // Update last_seen and confirmed=1 (first successful record)
    db()->prepare("
        UPDATE sensors
        SET last_seen = NOW(),
            confirmed = 1
        WHERE id = :id
    ")->execute([':id' => $sensorId]);

    jsonResponse([
        'ok'         => true,
        'sensor_id'  => $sensorId,
        'reading_id' => $readingId,
        'stored'     => $fields,
    ]);
}

// ─────────────────────────────────────────────────────────
// GET register — register a new sensor by coordinates
//
// Called from the index.php form or directly.
// Creates a record with confirmed=0.
// Within 3 min it must receive ?action=reading, otherwise it is deleted.
//
// URL: /api/sensors.php?action=register&lat=54.6872000&lng=25.2797000
// ─────────────────────────────────────────────────────────
if ($action === 'register') {
    $lat = getFloat('lat', -90,  90);
    $lng = getFloat('lng', -180, 180);
    $force = isset($_GET['force']) && $_GET['force'] === '1';
    // Indoor (0, default) or outdoor (1) sensor.
    // If the field is not provided — indoor by default (0).
    $isOutdoor = (isset($_GET['is_outdoor']) && ($_GET['is_outdoor'] === '1' || $_GET['is_outdoor'] === 'true')) ? 1 : 0;

    if ($lat === null || $lng === null) {
        jsonResponse([
            'error' => 'lat ir lng privalomi (7 dešimtainių ženklų tikslumas)',
            'pvz'   => '?action=register&lat=54.6872000&lng=25.2797000',
        ], 400);
    }

    // Is there already a sensor at these coordinates (confirmed or pending)?
    $existsStmt = db()->prepare(
        "SELECT COUNT(*) FROM sensors WHERE lat = :lat AND lng = :lng"
    );
    $existsStmt->execute([':lat' => $lat, ':lng' => $lng]);
    $coordsExist = (int)$existsStmt->fetchColumn() > 0;

    // If the coordinates are taken and the user has not confirmed — ask.
    if ($coordsExist && !$force) {
        jsonResponse([
            'ok'                 => false,
            'needs_confirmation' => true,
            'message'            => 'Šiose koordinatėse jau yra jutiklis. Registruoti naują toje pačioje vietoje?',
            'lat'                => $lat,
            'lng'                => $lng,
        ], 200);
    }

    try {
        // The prefix is chosen automatically by the nearest city
        $city = nearestCity($lat, $lng);

        // Pending sensor: mac = NULL (the MAC will be claimed on the first
        // at data-send time). Several NULLs at the same location
        // sugyvena unikaliame rakte.
        $stmt = db()->prepare(
            "INSERT INTO sensors (lat, lng, mac, is_outdoor, city_prefix) VALUES (:lat, :lng, NULL, :outdoor, :prefix)"
        );
        $stmt->execute([':lat' => $lat, ':lng' => $lng, ':outdoor' => $isOutdoor, ':prefix' => $city['prefix']]);
        $id = (int)db()->lastInsertId();

        // Sequence number within the city (not the DB id):
        // how many sensors of this prefix have id <= the new one
        $seqStmt = db()->prepare(
            "SELECT COUNT(*) FROM sensors WHERE city_prefix = :p AND id <= :id"
        );
        $seqStmt->execute([':p' => $city['prefix'], ':id' => $id]);
        $seq   = (int)$seqStmt->fetchColumn();
        $label = $city['prefix'] . $seq;

        jsonResponse([
            'ok'        => true,
            'sensor_id' => $id,
            'label'     => $label,
            'city'      => $city['city'],
            'distance_km' => $city['distance_km'],
            'geo_source'  => $city['source'] ?? 'local',
            'warning'     => $city['geo_error'] ?? null,
            'confirmed' => false,
            'info'      => 'Jutiklis laukia patvirtinimo. Per 3 min siųskite ?action=reading su šiomis koordinatėmis.',
            'reading_url' => "?action=reading&lat={$lat}&lng={$lng}&temperature=XX&humidity=XX",
        ], 201);

    } catch (PDOException $e) {
        // 23000 can mean TWO things:
        //  (a) a real duplicate (lat+lng+mac already exists) — only for confirmed ones;
        //  (b) sena schema su `mac NOT NULL` — INSERT NULL meta „cannot be null".
        // We distinguish by the error text.
        $msg = $e->getMessage();
        if (stripos($msg, 'cannot be null') !== false || stripos($msg, '1048') !== false) {
            jsonResponse([
                'error' => 'Sena duomenų bazės schema: stulpelis `mac` yra NOT NULL. '
                         . 'Atnaujinkite schemą per admin.php (Jutiklių valdymas → schemos atnaujinimas) '
                         . 'arba įvykdykite: ALTER TABLE sensors MODIFY mac VARCHAR(17) NULL DEFAULT NULL;',
                'code'  => 'schema_outdated',
            ], 500);
        }
        if ($e->getCode() === '23000') {
            // A real duplicate (same lat+lng+mac). With mac=NULL this should not
            // happen (NULL allows several), so we reach here only for a confirmed MAC.
            $existing = db()->prepare(
                "SELECT id, CONCAT(city_prefix, (
                    SELECT COUNT(*) FROM sensors s2
                    WHERE s2.city_prefix = sensors.city_prefix AND s2.id <= sensors.id
                 )) AS label, confirmed
                 FROM sensors WHERE lat = :lat AND lng = :lng"
            );
            $existing->execute([':lat' => $lat, ':lng' => $lng]);
            $row = $existing->fetch();
            jsonResponse([
                'error'     => 'Jutiklis su šiomis koordinatėmis jau užregistruotas',
                'sensor_id' => (int)$row['id'],
                'label'     => $row['label'],
                'confirmed' => (bool)$row['confirmed'],
            ], 409);
        }
        throw $e;
    }
}

// ─────────────────────────────────────────────────────────
// GET delete — manually delete a sensor by id
//
// URL: /api/sensors.php?action=delete&id=N
// ─────────────────────────────────────────────────────────
if ($action === 'clear_readings') {
    requireAdminPasswordApi(); // Requires a session AND a password

    $id = (int)($_POST['id'] ?? $_GET['id'] ?? 0);
    if ($id <= 0) jsonResponse(['error' => 'Trūksta arba neteisingas id'], 400);

    // Check whether the sensor exists
    $check = db()->prepare("SELECT id FROM sensors WHERE id = :id");
    $check->execute([':id' => $id]);
    if (!$check->fetch()) {
        jsonResponse(['error' => 'Jutiklis nerastas'], 404);
    }

    $stmt = db()->prepare("DELETE FROM readings WHERE sensor_id = :id");
    $stmt->execute([':id' => $id]);

    auditLog('clear_readings', $id, $stmt->rowCount() . ' readings deleted');
    jsonResponse(['ok' => true, 'sensor_id' => $id, 'deleted_readings' => $stmt->rowCount()]);
}

if ($action === 'delete') {
    requireAdminPasswordApi(); // Requires a session AND a password

    $id = (int)($_POST['id'] ?? $_GET['id'] ?? 0);
    if ($id <= 0) jsonResponse(['error' => 'Trūksta arba neteisingas id'], 400);

    $stmt = db()->prepare("DELETE FROM sensors WHERE id = :id");
    $stmt->execute([':id' => $id]);

    if ($stmt->rowCount() === 0) {
        jsonResponse(['error' => 'Jutiklis nerastas'], 404);
    }

    auditLog('delete_sensor', $id, 'sensor + readings cascade');
    jsonResponse(['ok' => true, 'deleted_sensor_id' => $id]);
}

// ─────────────────────────────────────────────────────────
// POST set_secret — set / clear a sensor's HMAC shared-secret
//   id     = sensor id
//   secret = the shared secret (empty → clears it, HMAC off)
// The SAME value must be configured in the sensor's firmware so that
// signed readings (?action=reading&...&sig=) can be verified.
// The stored secret is never returned by the API.
// ─────────────────────────────────────────────────────────
if ($action === 'set_secret') {
    requireAdminPasswordApi(); // requires a session AND a password

    $id = (int)($_POST['id'] ?? $_GET['id'] ?? 0);
    if ($id <= 0) jsonResponse(['error' => 'Trūksta arba neteisingas id'], 400);

    $secret = trim((string)($_POST['secret'] ?? $_GET['secret'] ?? ''));
    if ($secret !== '' && (strlen($secret) < 8 || strlen($secret) > 64)) {
        jsonResponse(['error' => 'Secret turi būti 8–64 simbolių.', 'code' => 'invalid_secret'], 400);
    }

    $stmt = db()->prepare("UPDATE sensors SET secret = :secret WHERE id = :id");
    $stmt->execute([':secret' => ($secret === '' ? null : $secret), ':id' => $id]);

    // rowCount() == 0 can mean "not found" OR "value unchanged" — verify existence.
    if ($stmt->rowCount() === 0) {
        $chk = db()->prepare("SELECT COUNT(*) FROM sensors WHERE id = :id");
        $chk->execute([':id' => $id]);
        if ((int)$chk->fetchColumn() === 0) {
            jsonResponse(['error' => 'Jutiklis nerastas'], 404);
        }
    }

    auditLog($secret === '' ? 'clear_sensor_secret' : 'set_sensor_secret', $id,
             $secret === '' ? 'HMAC disabled' : 'HMAC secret set');
    jsonResponse([
        'ok'        => true,
        'sensor_id' => $id,
        'hmac'      => $secret !== '',
        'message'   => $secret !== ''
            ? 'HMAC parašas įjungtas. Tą patį secret įrašykite į jutiklio firmware.'
            : 'HMAC parašas išjungtas šiam jutikliui.',
    ]);
}

// ─────────────────────────────────────────────────────────
// POST clear_readings_bulk — clear data of several sensors
//   ids = "1,2,3" (kableliais atskirti ID)
// ─────────────────────────────────────────────────────────
if ($action === 'clear_readings_bulk') {
    requireAdminPasswordApi();

    $ids = parseIdList($_POST['ids'] ?? $_GET['ids'] ?? '');
    if (empty($ids)) jsonResponse(['error' => 'Trūksta arba neteisingas ids'], 400);

    $ph = implode(',', array_fill(0, count($ids), '?'));
    $stmt = db()->prepare("DELETE FROM readings WHERE sensor_id IN ($ph)");
    $stmt->execute($ids);

    auditLog('clear_readings_bulk', null,
        count($ids) . ' sensors, ' . $stmt->rowCount() . ' readings deleted');
    jsonResponse([
        'ok' => true,
        'sensors_affected' => count($ids),
        'deleted_readings' => $stmt->rowCount(),
    ]);
}

// ─────────────────────────────────────────────────────────
// POST delete_bulk — delete several sensors (with data, CASCADE)
//   ids = "1,2,3"
// ─────────────────────────────────────────────────────────
if ($action === 'delete_bulk') {
    requireAdminPasswordApi();

    $ids = parseIdList($_POST['ids'] ?? $_GET['ids'] ?? '');
    if (empty($ids)) jsonResponse(['error' => 'Trūksta arba neteisingas ids'], 400);

    $ph = implode(',', array_fill(0, count($ids), '?'));
    $stmt = db()->prepare("DELETE FROM sensors WHERE id IN ($ph)");
    $stmt->execute($ids);

    auditLog('delete_bulk', null, $stmt->rowCount() . ' sensors deleted (cascade)');
    jsonResponse(['ok' => true, 'deleted_sensors' => $stmt->rowCount()]);
}

// ─────────────────────────────────────────────────────────
// POST clear_region — clear data of a whole region (city_prefix)
//   region = "VLN"
// ─────────────────────────────────────────────────────────
if ($action === 'clear_region') {
    requireAdminPasswordApi();

    $region = strtoupper(trim((string)($_POST['region'] ?? $_GET['region'] ?? '')));
    if ($region === '' || !preg_match('/^[A-Z0-9]{1,10}$/', $region)) {
        jsonResponse(['error' => 'Trūksta arba neteisingas region'], 400);
    }

    // Deletes the readings of all sensors in that region (sensors remain).
    $stmt = db()->prepare("
        DELETE r FROM readings r
        JOIN sensors s ON s.id = r.sensor_id
        WHERE s.city_prefix = :region
    ");
    $stmt->execute([':region' => $region]);

    auditLog('clear_region', null, "region=$region, " . $stmt->rowCount() . ' readings deleted');
    jsonResponse([
        'ok' => true,
        'region' => $region,
        'deleted_readings' => $stmt->rowCount(),
    ]);
}

// ─────────────────────────────────────────────────────────
// POST delete_region — delete all sensors of a region (with data)
//   region = "VLN"
// ─────────────────────────────────────────────────────────
if ($action === 'delete_region') {
    requireAdminPasswordApi();

    $region = strtoupper(trim((string)($_POST['region'] ?? $_GET['region'] ?? '')));
    if ($region === '' || !preg_match('/^[A-Z0-9]{1,10}$/', $region)) {
        jsonResponse(['error' => 'Trūksta arba neteisingas region'], 400);
    }

    $stmt = db()->prepare("DELETE FROM sensors WHERE city_prefix = :region");
    $stmt->execute([':region' => $region]);

    auditLog('delete_region', null, "region=$region, " . $stmt->rowCount() . ' sensors deleted (cascade)');
    jsonResponse([
        'ok' => true,
        'region' => $region,
        'deleted_sensors' => $stmt->rowCount(),
    ]);
}

// ─────────────────────────────────────────────────────────
// GET geotest — city recognition diagnostics
//
// Use when a sensor gets the wrong city prefix.
// Shows which source matched and why the Google API
// does (not) work — without writing to the DB.
//
// URL: /api/sensors.php?action=geotest&lat=54.05&lng=24.95
// ─────────────────────────────────────────────────────────
if ($action === 'geotest') {
    $lat = getFloat('lat', -90,  90);
    $lng = getFloat('lng', -180, 180);
    if ($lat === null || $lng === null) {
        jsonResponse(['error' => 'lat ir lng privalomi'], 400);
    }

    $debug = null;
    $google = geocodeCity($lat, $lng, $debug);
    $result = nearestCity($lat, $lng);

    jsonResponse([
        'coordinates'   => ['lat' => $lat, 'lng' => $lng],
        'final_result'  => $result,
        'google_api'    => [
            'works'   => $google !== null,
            'status'  => $debug['status'] ?? null,
            'error'   => $debug['error'] ?? null,
            'result'  => $google,
        ],
        'hint' => $google === null
            ? 'Google Geocoding neveikia. Patikrinkite: 1) Geocoding API įjungtas Cloud Console; 2) raktas BE HTTP referrer ribojimo (serverio užklausoms reikia IP ribojimo arba be ribojimų); 3) billing įjungtas.'
            : 'Google Geocoding veikia teisingai.',
    ]);
}

// ─────────────────────────────────────────────────────────
// Unrecognized action
// ─────────────────────────────────────────────────────────
jsonResponse([
    'error'    => 'Nežinomas action',
    'galimi'   => ['map_data','history','reading','register','delete','clear_readings','geotest'],
], 404);
